// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLw7IgYpR-cdlDPyn30E1Y0B9ChdzmAEw',
    appId: '1:24956809392:web:d3f1e6e88dde872d46cb75',
    messagingSenderId: '24956809392',
    projectId: 'smart-biochip',
    authDomain: 'smart-biochip.firebaseapp.com',
    storageBucket: 'smart-biochip.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcU3WaRL46P8oL6BCuxfTqfIwkDfJPdJw',
    appId: '1:24956809392:android:8a86aa5e13b811ff46cb75',
    messagingSenderId: '24956809392',
    projectId: 'smart-biochip',
    storageBucket: 'smart-biochip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEtlC_vBNTZ7ae3CWs7cLfaYynWjreY6Q',
    appId: '1:24956809392:ios:cad24ff4d99d572e46cb75',
    messagingSenderId: '24956809392',
    projectId: 'smart-biochip',
    storageBucket: 'smart-biochip.appspot.com',
    iosBundleId: 'com.example.bpapp',
  );
}
